snac-cooperative/snac

install/sql_files/schema.sql, src/snac/server/ServerExecutor.php, src/snac/server/database/DBUtil.php, src/snac/server/database/SQL.php, src/virtualhosts/www/javascript/edit_scripts.js
Closes issue #92 API has race conditions
=> Reject duplicate resources

src/snac/client/webui/WebUI.php, src/snac/client/webui/WebUIExecutor.php, src/snac/client/webui/templates/message_list.html, src/snac/server/Server.php, src/snac/server/ServerExecutor.php, src/snac/server/database/DBUser.php, src/snac/server/database/SQL.php, src/virtualhosts/www/javascript/messaging_scripts.js
=> View sent messages

src/snac/client/webui/templates/history_page.html, src/snac/server/database/DBUtil.php, src/snac/server/database/SQL.php
I added a special history status on the history page that shows more information when a constellation has been merged or split.
=> Added merge/split information to the history page

src/snac/client/rest/commands.json, src/snac/client/webui/WebUI.php, src/snac/client/webui/WebUIExecutor.php, src/snac/client/webui/templates/api_test_page.html, src/snac/client/webui/templates/page_navigation.html, src/snac/client/webui/templates/view_page.html, src/snac/client/webui/templates/view_page_full.html, src/snac/server/Server.php, src/snac/server/ServerExecutor.php, src/snac/server/elastic/ElasticSearchUtil.php, src/snac/util/EACCPFSerializer.php
I'm making the rest api commands public and adding an elastic search pass through function.  It's pretty nifty, I think, but I'd like you to test it out first.
I also added the api "playground."  There's a link when logged in, but it's accessible even when not if you know the url (api_test).  Thoughts?
=> Rest elastic

src/snac/client/webui/templates/search_page.html, src/virtualhosts/www/javascript/search.js
=> Fixed bug in the search scripts

src/snac/client/rest/commands.json, src/snac/data/SNACDate.php, src/snac/server/Server.php, src/snac/server/ServerExecutor.php, src/snac/util/EACCPFParser.php, src/snac/util/LocalVocabulary.php
Added a pathway for parsing EAC in the server and rest api.   Cleaned up the parser a little bit.
=> Parser updates

src/snac/client/webui/templates/resources/edit.html, src/snac/client/webui/templates/resources/search.html, src/snac/client/webui/templates/resources/view.html, src/virtualhosts/www/javascript/scripts.js
Improved resource chart styling. Added js for feedback button to resource pages.
Closes #144
=> Resource updates

src/snac/client/webui/templates/edit_components.html, src/snac/client/webui/templates/edit_page.html, src/virtualhosts/www/javascript/edit_scripts.js, src/virtualhosts/www/javascript/name_parser.js
- Add auto name-parsing button for Persons
=> Name parser

src/snac/client/webui/templates/resources/search.html, src/virtualhosts/www/javascript/select_loaders.js
Adds a few styling and view changes to improve the resource search page.
=> New resource features

src/virtualhosts/www/.htaccess
Add rewrite rule to catch requests for edit_parts before constellation has id and version.
=> Fix 404 error for edit_parts on new constellation page

src/snac/client/webui/templates/view_page.html, src/snac/client/webui/templates/view_page_full.html
Update from just using wikipedia.org SameAs links to allowing for wikidata.
=> Check for all wiki foundation sites to query for profile picture.

composer.json, composer.lock
- Google+ APIs and sign-ins are being deprecated. Update Oauth2 libraries so we can use Google Sign-in with OpenID instead.
=> Update Oauth2 dependencies

src/snac/client/openrefine/OpenRefine.php, src/snac/client/webui/WebUI.php, src/snac/client/webui/WebUIExecutor.php, src/snac/client/webui/templates/snippet_page.html
Adds a preview view (snippet page) to the OpenRefine endpoint.  Partially addresses #203.
=> Openrefine Preview

src/virtualhosts/www/javascript/save_actions.js
- Validates that there are no edited components with empty term fields.
- Extract nameEntry and entityType validation into validateConstellation() function.
Fixes #253
=> Validate Constellation before saving in frontend

src/snac/client/webui/languages/english.json, src/snac/client/webui/templates/detailed_preview_page.html, src/snac/client/webui/templates/detailed_view_page.html, src/snac/client/webui/templates/edit_components.html, src/snac/client/webui/templates/edit_page.html, src/snac/client/webui/templates/edit_tabs/nameEntries.html, src/snac/client/webui/templates/maybesame_diff_page.html, src/snac/client/webui/templates/widgets.html, src/snac/client/webui/util/ConstellationPostMapper.php, src/snac/server/database/DBUtil.php, src/virtualhosts/www/css/snac.css, src/virtualhosts/www/javascript/select_loaders.js
=> Source cite update/267/jhg2v

src/snac/client/webui/templates/resources/search.html
Update loadVocabSelectOptions call to match with revised promise handling.
Fixes #269
=> Fix loadVocabSelectOptions on resources/search.html

composer.json, src/snac/server/mailer/Mailer.php
Upgrade PHPMailer to fix spam-filtering problem for some users.
=> Upgrade PHPMailer to 6.0

src/snac/client/webui/WebUI.php, src/snac/client/webui/templates/browse_page.html, src/snac/client/webui/templates/page_navigation.html, src/virtualhosts/www/javascript/browse_scripts.js
- Hide editor buttons and checkmarks for non-logged-in users on Browse page
- Show Browse and Resources links on public navbar
=> Make Browse and Resource links to public

src/snac/Config_dist.php, src/snac/client/webui/WebUI.php, src/snac/client/webui/display/Display.php, src/snac/client/webui/templates/page_navigation.html
Added new functions that will be called from Laravel to Login using an
OAuth Token. And also close and destroy the session after logging out in
the Laravel Application.
=> Add Single Sign On to Integrate with SNAC-Laravel

src/snac/server/ServerExecutor.php
This is an update to #213 since there are some vocabulary terms that do not require `entity_type`.  However, we may in the future updated vocabulary system want to require that `entity_type` is provided for types that need it (activity, name components, etc).
=> Fixed entity type to not be required on search

src/snac/client/openrefine/ORConstellationMapper.php, src/snac/client/openrefine/OpenRefine.php, src/snac/server/ServerExecutor.php, src/snac/server/identityReconciliation/ReconciliationEngine.php, src/snac/server/identityReconciliation/stages/SameAs.php, src/snac/server/identityReconciliation/weights/SameAsStaticWeight.php, src/virtualhosts/openrefine/.htaccess, src/virtualhosts/openrefine/index.php
I know I need more comments in the ORConstellationMapper, but I'd like to get your thoughts.
=> Openrefine Suggest API and SameAs

src/snac/util/EADParser.php
=> Added post-processing to EAD Parser

src/snac/client/openrefine/ORConstellationMapper.php, src/snac/client/openrefine/OpenRefine.php, src/snac/client/util/LaravelUtil.php, src/snac/server/database/DBUtil.php
Enable concept reconciliation through OpenRefine endpoint
=> OpenRefine reconciliation
